version: '3'

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - pgdata:/var/lib/postgresql/data

  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PIP_EXTRA_INDEX_URL
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: >
      bash -c "cd /app
      && python manage.py migrate
      && python manage.py collectstatic --no-input
      && python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db

volumes:
  pgdata:
networks:
  db:
