# Generated by Django 4.2.16 on 2024-12-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_license_software_alter_order_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=12, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
